cmake_minimum_required(VERSION 3.15)
project(mik64_converter)
if(NOT TARGET mik64_converter)
    add_subdirectory(lib/mik64_logger)
    file(GLOB CONVERTER_SOURCES "cpp/*.cpp")
    add_library(mik64_converter STATIC ${CONVERTER_SOURCES})
    add_library(mik64::converter ALIAS mik64_converter)
    target_include_directories(mik64_converter PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/h)
    target_compile_features(mik64_converter PRIVATE cxx_std_17)

    target_link_libraries(mik64_converter PRIVATE mik64::logger)
endif()
add_executable(mik64_converter_test main.cpp)
target_link_libraries(mik64_converter_test PRIVATE mik64::converter)